#ifndef _SHELL_H_
#define _SHELL_H_

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <sys/stat.h>
#include <limits.h>
#include <fcntl.h>
#include <errno.h>

/* for read/write buffers */
#define READ_BUF_SIZE 1024
#define WRITE_BUF_SIZE 1024
#define BUF_FLUSH -1

/* for command chaining */
#define CMD_NORM	0
#define CMD_OR		1
#define CMD_AND		2
#define CMD_CHAIN	3

/* for convert_number() */
#define CONVERT_LOWERCASE	1
#define CONVERT_UNSIGNED	2

/* 1 if using system getline() */
#define USE_GETLINE 0
#define USE_STRTOK 0

#define HIST_FILE	".simple_shell_history"
#define HIST_MAX	4096

extern char **environ;


/**
 * struct liststr - singly linked list
 * @num: the numerical field
 * @cord: a string
 * @next: makes a reference to the next node
 */
typedef struct liststr
{
	int num;
	char *cord;
	struct liststr *next;
} list_val;

/**
 * struct passinfo - includes pseudo-arguments for use in functions,
 * allowing for a standardized prototype for the function pointer struct
 * @arg: a string containing arguments generated by getline
 * @argv: a string array derived from arg
 * @path: a route in string for the current command
 * @argc: the number of arguments
 * @line_count: the number of errors
 * @err_num: the error code for exit()s
 * @linecount_flag: if this line of input is counted
 * @fname: the program’s file name
 * @env: local copy of the linked list environ
 * @environ: a customized copy of environ derived from LL env
 * @history: the node of history
 * @alias: the node of the alias
 * @env_changed: if the environ was altered
 * @status: the return status of the most recently executed command
 * @cmd_buf: if chaining is enabled, the location of the reference to cmd_buf
 * @cmd_buf_type: CMD_type ||, &&, ;
 * @readval: the val to read line input from
 * @histcount: the amount of historical lines
 */
typedef struct passinfo
{
	char *arg;
	char **argv;
	char *path;
	int argc;
	unsigned int line_count;
	int err_num;
	int linecount_flag;
	char *fname;
	list_val *env;
	list_val *history;
	list_val *alias;
	char **environ;
	int env_changed;
	int status;

	char **cmd_buf; /* pointer to cmd ; chain buffer, for memory mangement */
	int cmd_buf_type; /* CMD_type ||, &&, ; */
	int readval;
	int histcount;
} info_val;

#define INFO_INIT \
{NULL, NULL, NULL, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, \
		0, 0, 0}

/**
 * struct builtin - includes a built-in string and an associated function
 * @type: the builtin command flag
 * @func: the function
 */
typedef struct builtin
{
	char *type;
	int (*func)(info_val *);
} builtin_table;


/* toem_atoi.c */
int interactive(info_val *);
int is_delim(char, char *);
int _isalpha(int);
int _atoi(char *);

/* toem_builtin.c */
int _myexit(info_val *);
int _mycd(info_val *);
int _myhelp(info_val *);

/* toem_builtin1.c */
int _myhistory(info_val *);
int _myalias(info_val *);

/* toem_environ.c */
char *_getenv(info_val *, const char *);
int _myenv(info_val *);
int _mysetenv(info_val *);
int _myunsetenv(info_val *);
int populate_env_list(info_val *);

/* toem_errors.c */
void _eputs(char *);
int _eputchar(char);
int _putval(char valcum, int val);
int _putsval(char *cord, int val);

/* toem_errors1.c */
int _erratoi(char *);
void print_error(info_val *, char *);
int print_d(int, int);
char *convert_number(long int, int, int);
void remove_comments(char *);

/* toem_exits.c */
char *_strncpy(char *, char *, int);
char *_strncat(char *, char *, int);
char *_strchr(char *, char);

/*toem_getline.c */
ssize_t get_input(info_val *);
int _getline(info_val *, char **, size_t *);
void sigintHandler(int);

/* toem_getenv.c */
char **get_environ(info_val *);
int _unsetenv(info_val *, char *);
int _setenv(info_val *, char *, char *);

/* toem_getinfo.c */
void clear_info(info_val *);
void set_info(info_val *, char **);
void free_info(info_val *, int);

/* toem_history.c */
char *get_history_file(info_val *info);
int write_history(info_val *info);
int read_history(info_val *info);
int build_history_list(info_val *info, char *buf, int linecount);
int renumber_history(info_val *info);

/* toem_lists.c */
list_val *add_node(list_val **, const char *, int);
list_val *add_node_end(list_val **, const char *, int);
size_t print_list_str(const list_val *);
int delete_node_at_index(list_val **, unsigned int);
void free_list(list_val **);

/* toem_lists1.c */
size_t list_len(const list_val *);
char **list_to_strings(list_val *);
size_t print_list(const list_val *);
list_val *node_starts_with(list_val *, char *, char);
ssize_t get_node_index(list_val *, list_val *);

/* toem_memory.c */
int bfree(void **);

/* toem_parser.c */
int is_cmd(info_val *, char *);
char *dup_chars(char *, int, int);
char *find_path(info_val *, char *, char *);

/* toem_realloc.c */
char *_memset(char *, char, unsigned int);
void ffree(char **);
void *_realloc(void *, unsigned int, unsigned int);

/* toem_shloop.c */
int hsh(info_val *, char **);
int find_builtin(info_val *);
void find_cmd(info_val *);
void fork_cmd(info_val *);

/* loophsh.c */
int loophsh(char **);

/* toem_string.c */
int _strlen(char *);
int _strcmp(char *, char *);
char *starts_with(const char *, const char *);
char *_strcat(char *, char *);

/* toem_string1.c */
char *_strcpy(char *, char *);
char *_strdup(const char *);
void _puts(char *);
int _putchar(char);

/* toem_tokenizer.c */
char **stringwin(char *, char *);
char **stringwins(char *, char);

/* toem_vars.c */
int is_chain(info_val *, char *, size_t *);
void check_chain(info_val *, char *, size_t *, size_t, size_t);
int replace_alias(info_val *);
int replace_vars(info_val *);
int replace_string(char **, char *);

#endif
